language: php

php:
  - 8.0
  - 8.1

env:
  global:
    - CI: 'true'
    - TEST_OUTPUT_STYLE: 'pretty'
    - PHPCS_REPORT_STYLE: 'full'
    - COMPOSER_OPTIONS: '--optimize-autoloader'
  jobs:
    - SYMFONY_VERSION: '^5.4'
    - SYMFONY_VERSION: '^6.0'

jobs:
  fast_finish: true

before_install:
  # remove xdebug to speed up build
  - phpenv config-rm xdebug.ini || true

install:
  - composer require symfony/http-kernel:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION
  - composer require --dev symfony/routing:$SYMFONY_VERSION symfony/framework-bundle:$SYMFONY_VERSION
  - make build
script:
  - make test-technical
  - make test-functional

cache:
  directories:
    - $HOME/.composer
    - vendor

branches:
  except:
  - /.*\-dev$/
  - /.*\-patch(\-\d+)?$/
  - /^dev-.*$/
